# Generated by Django 4.2.6 on 2023-11-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='comision',
            new_name='codigo',
        ),
    ]
