# Generated by Django 4.2.7 on 2023-11-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_empleados', '0005_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
